run-name: Test
on:
  workflow_dispatch # To support manual trigger.

jobs:
  test-run:
    runs-on: ubuntu-latest

    steps:
      - name: Testing action
        id: testing-action
        uses: ajayg2808/Iteration-Report@main
        with:
          owner: ajayg2808
          number: 6
          token: ${{ secrets.ACCESS_TOKEN }}
          iteration-field: Iteration
          iteration: Iteration 1